.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.Dd 4/20/11               \" DATE 
.Dt ubcontrol 1       
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm ubcontrol
.Nd control some operations of ubiquity.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl --reset     
.Op Fl --loglevel Ar level  
.Sh DESCRIPTION          \" Section Header - required - don't modify
The
.Nm
utility provides a way to control certain options of the ubiquity daemon
.Pp                     
Options:
.Bl -tag -width -indent   
.It --reset 
disables sharing files and moves all information about the shared files 
and folders to a separate location for deletion or later inspection.
.It --loglevel Ar level
change the log level from 0-7, corresponding to levels defined in syslog.h
.El                     
.Pp
.Sh SEE ALSO 
.Xr ubd 1
